---
-
  name: Update Lyfebloc Edge binary
  hosts:
    - all
  become: yes
  tasks:
    ## update & upgrade system
    - name: Update & upgrade system
      apt:
        upgrade: yes
        update_cache: yes

    ## stop lyfebloc-edge service
    - name: Stop Lyfebloc Edge service
      systemd:
        state: stopped
        name: lyfebloc-edge

    ## get the latest release
    - name: Get latest release link
      uri:
        url: https://api.github.com/repos/lyfeblocnetwork/lyfebloc-edge/releases/latest
        return_content: true
      register: edge_release

    ## download the latest release
    - name: Download latest Lyfebloc Edge release
      get_url:
        url: "{{ edge_release.json.assets[3].browser_download_url }}"
        dest: /tmp/lyfebloc-edge.tar.gz
        force: yes

    ## create temp dir for release
    - name: Create temp dir for Lyfebloc Edge release
      file:
        path: /tmp/lyfebloc-edge
        state: directory

    ## unpack release tar
    - name: Unpack Lyfebloc Edge release
      unarchive:
        remote_src: yes
        src: /tmp/lyfebloc-edge.tar.gz
        dest: /tmp/lyfebloc-edge

    ## set lyfebloc-edge to PATH
    - name: Place Lyfebloc Edge binary to PATH
      copy:
        remote_src: yes
        src: /tmp/lyfebloc-edge/lyfebloc-edge
        dest: /usr/local/bin/
        mode: a+x
        force: yes

    ## remove release temp dir
    - name: Remove temp Lyfebloc Edge release dir
      file:
        state: absent
        path: /tmp/lyfebloc-edge

    ## start Lyfebloc Edge service
    - name: Start lyfebloc-edge service
      systemd:
        state: restarted
        name: lyfebloc-edge
        daemon_reload: yes
        enabled: yes